-- Generated from the frozen V6.1 RBAC matrix. Do not hand-edit the seed section.
BEGIN;

ALTER TABLE role_catalog DROP CONSTRAINT IF EXISTS role_catalog_scope_type_check;
ALTER TABLE role_catalog ADD CONSTRAINT role_catalog_scope_type_check
  CHECK (scope_type IN ('PLATFORM','CHANNEL','TENANT','STORE','INSTALLATION'));

ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS access_scope text;
UPDATE role_permissions SET access_scope = 'ALL' WHERE access_scope IS NULL;
ALTER TABLE role_permissions ALTER COLUMN access_scope SET NOT NULL;
ALTER TABLE role_permissions DROP CONSTRAINT IF EXISTS role_permissions_access_scope_check;
ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_access_scope_check
  CHECK (access_scope IN ('ALL','ASSIGNED','CONDITIONAL','DUAL','GRANT','JIT_READ','OWN','REGION','STORE','TENANT'));

CREATE TABLE user_sessions (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  session_id text NOT NULL,
  user_id uuid NOT NULL,
  refresh_token_hash text,
  device_fingerprint_hash text,
  auth_level text NOT NULL DEFAULT 'PASSWORD' CHECK (auth_level IN ('PASSWORD','MFA')),
  risk_level text NOT NULL DEFAULT 'LOW' CHECK (risk_level IN ('LOW','MEDIUM','HIGH','BLOCKED')),
  issued_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  revoke_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, session_id),
  FOREIGN KEY (tenant_id, user_id) REFERENCES tenant_memberships(tenant_id, user_id) ON DELETE CASCADE,
  CHECK (expires_at > issued_at),
  CHECK ((revoked_at IS NULL AND revoke_reason IS NULL) OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL))
);

CREATE INDEX user_sessions_active_idx ON user_sessions(tenant_id, user_id, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE tenant_entitlement_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  subscription_id uuid NOT NULL,
  plan_code text NOT NULL REFERENCES plans(plan_code),
  subscription_version integer NOT NULL CHECK (subscription_version > 0),
  entitlements jsonb NOT NULL CHECK (jsonb_typeof(entitlements) = 'object'),
  effective_from timestamptz NOT NULL,
  effective_to timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, subscription_id, subscription_version),
  FOREIGN KEY (tenant_id, subscription_id) REFERENCES tenant_subscriptions(tenant_id, id),
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE ai_usage_ledger_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  subscription_id uuid,
  meter_code text NOT NULL,
  source_type text NOT NULL CHECK (source_type IN ('MODEL','IMAGE','OCR','ASR','VECTOR','WORKFLOW')),
  source_id text NOT NULL,
  provider text NOT NULL,
  model_code text,
  quantity numeric(20,6) NOT NULL CHECK (quantity > 0),
  cost_cents bigint NOT NULL CHECK (cost_cents >= 0),
  occurred_at timestamptz NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  trace_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, source_type, source_id, meter_code),
  FOREIGN KEY (tenant_id, subscription_id) REFERENCES tenant_subscriptions(tenant_id, id)
);

CREATE TRIGGER tenant_entitlement_snapshots_immutable
BEFORE UPDATE OR DELETE ON tenant_entitlement_snapshots
FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();

CREATE TRIGGER ai_usage_ledger_entries_immutable
BEFORE UPDATE OR DELETE ON ai_usage_ledger_entries
FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();

ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY user_sessions_tenant_isolation ON user_sessions
  USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id());
ALTER TABLE tenant_entitlement_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_entitlement_snapshots_tenant_isolation ON tenant_entitlement_snapshots
  USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id());
ALTER TABLE ai_usage_ledger_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY ai_usage_ledger_entries_tenant_isolation ON ai_usage_ledger_entries
  USING (tenant_id = app.current_tenant_id()) WITH CHECK (tenant_id = app.current_tenant_id());

INSERT INTO role_catalog(role_code, role_name, scope_type, description) VALUES
  ('PLATFORM_ADMIN','平台安全管理员','PLATFORM','V6.1 frozen RBAC role: 平台安全管理员'),
  ('PLATFORM_OPS','平台运营','PLATFORM','V6.1 frozen RBAC role: 平台运营'),
  ('PLATFORM_FINANCE','平台财务','PLATFORM','V6.1 frozen RBAC role: 平台财务'),
  ('CHANNEL_PARTNER','区县合作伙伴','CHANNEL','V6.1 frozen RBAC role: 区县合作伙伴'),
  ('MERCHANT_OWNER','商家负责人','TENANT','V6.1 frozen RBAC role: 商家负责人'),
  ('STORE_MANAGER','店长','STORE','V6.1 frozen RBAC role: 店长'),
  ('CUSTOMER_SERVICE','客服','STORE','V6.1 frozen RBAC role: 客服'),
  ('FINANCE','商家财务','TENANT','V6.1 frozen RBAC role: 商家财务'),
  ('MARKETER','商家运营','STORE','V6.1 frozen RBAC role: 商家运营'),
  ('VERIFIER','核销员','STORE','V6.1 frozen RBAC role: 核销员'),
  ('AUDITOR','审计员','TENANT','V6.1 frozen RBAC role: 审计员'),
  ('PLUGIN_RUNTIME','插件运行身份','INSTALLATION','V6.1 frozen RBAC role: 插件运行身份'),
  ('BUSINESS_DEVELOPER','商务人员','CHANNEL','V6.1 frozen RBAC role: 商务人员'),
  ('INVESTMENT_OPERATOR','招商公司运营','CHANNEL','V6.1 frozen RBAC role: 招商公司运营'),
  ('REGIONAL_PROVIDER','区县服务商','CHANNEL','V6.1 frozen RBAC role: 区县服务商')
ON CONFLICT (role_code) DO UPDATE SET
  role_name = EXCLUDED.role_name,
  scope_type = EXCLUDED.scope_type,
  description = EXCLUDED.description;

INSERT INTO permission_catalog(permission_code, domain, description, risk_level) VALUES
  ('delivery.read','delivery','V6.1 frozen permission delivery.read','MEDIUM'),
  ('delivery.create','delivery','V6.1 frozen permission delivery.create','HIGH'),
  ('delivery.execute','delivery','V6.1 frozen permission delivery.execute','HIGH'),
  ('delivery.accept','delivery','V6.1 frozen permission delivery.accept','HIGH'),
  ('merchant_profile.manage','merchant_profile','V6.1 frozen permission merchant_profile.manage','HIGH'),
  ('miniprogram.manage','miniprogram','V6.1 frozen permission miniprogram.manage','HIGH'),
  ('miniprogram.release.submit','miniprogram','V6.1 frozen permission miniprogram.release.submit','MEDIUM'),
  ('miniprogram.release.publish','miniprogram','V6.1 frozen permission miniprogram.release.publish','CRITICAL'),
  ('miniprogram.release.rollback','miniprogram','V6.1 frozen permission miniprogram.release.rollback','CRITICAL'),
  ('geo.read','geo','V6.1 frozen permission geo.read','MEDIUM'),
  ('geo.publish','geo','V6.1 frozen permission geo.publish','CRITICAL'),
  ('customer_service.read','customer_service','V6.1 frozen permission customer_service.read','MEDIUM'),
  ('customer_service.accept','customer_service','V6.1 frozen permission customer_service.accept','HIGH'),
  ('customer_service.send','customer_service','V6.1 frozen permission customer_service.send','HIGH'),
  ('customer_service.close','customer_service','V6.1 frozen permission customer_service.close','HIGH'),
  ('customer_profile.read','customer_profile','V6.1 frozen permission customer_profile.read','MEDIUM'),
  ('customer_profile.export','customer_profile','V6.1 frozen permission customer_profile.export','CRITICAL'),
  ('order.read','order','V6.1 frozen permission order.read','MEDIUM'),
  ('order.manage','order','V6.1 frozen permission order.manage','HIGH'),
  ('refund.request','refund','V6.1 frozen permission refund.request','HIGH'),
  ('refund.approve','refund','V6.1 frozen permission refund.approve','CRITICAL'),
  ('verification.execute','verification','V6.1 frozen permission verification.execute','HIGH'),
  ('reward_rule.manage','reward_rule','V6.1 frozen permission reward_rule.manage','HIGH'),
  ('finance.reconcile','finance','V6.1 frozen permission finance.reconcile','HIGH'),
  ('settlement.approve','settlement','V6.1 frozen permission settlement.approve','CRITICAL'),
  ('report.value.read','report','V6.1 frozen permission report.value.read','MEDIUM'),
  ('member.manage','member','V6.1 frozen permission member.manage','HIGH'),
  ('role.manage','role','V6.1 frozen permission role.manage','CRITICAL'),
  ('plugin.install','plugin','V6.1 frozen permission plugin.install','HIGH'),
  ('plugin.permission.grant','plugin','V6.1 frozen permission plugin.permission.grant','HIGH'),
  ('audit.read','audit','V6.1 frozen permission audit.read','MEDIUM'),
  ('tenant.suspend','tenant','V6.1 frozen permission tenant.suspend','CRITICAL'),
  ('support.jit_read','support','V6.1 frozen permission support.jit_read','MEDIUM'),
  ('merchant.intake.create','merchant','V6.1 frozen permission merchant.intake.create','HIGH'),
  ('merchant.intake.read','merchant','V6.1 frozen permission merchant.intake.read','MEDIUM'),
  ('merchant.intake.write','merchant','V6.1 frozen permission merchant.intake.write','MEDIUM'),
  ('merchant.intake.confirm','merchant','V6.1 frozen permission merchant.intake.confirm','MEDIUM'),
  ('revenue_right.read_own','revenue_right','V6.1 frozen permission revenue_right.read_own','MEDIUM'),
  ('revenue_right.read_all','revenue_right','V6.1 frozen permission revenue_right.read_all','MEDIUM'),
  ('revenue_right.create','revenue_right','V6.1 frozen permission revenue_right.create','HIGH'),
  ('revenue_right.transfer_request','revenue_right','V6.1 frozen permission revenue_right.transfer_request','HIGH'),
  ('revenue_right.transfer_approve','revenue_right','V6.1 frozen permission revenue_right.transfer_approve','CRITICAL'),
  ('revenue_right.suspend','revenue_right','V6.1 frozen permission revenue_right.suspend','MEDIUM'),
  ('distribution.read_own','distribution','V6.1 frozen permission distribution.read_own','MEDIUM'),
  ('distribution.read_all','distribution','V6.1 frozen permission distribution.read_all','MEDIUM'),
  ('distribution.cost.read','distribution','V6.1 frozen permission distribution.cost.read','MEDIUM'),
  ('distribution.lock','distribution','V6.1 frozen permission distribution.lock','HIGH'),
  ('distribution.pay','distribution','V6.1 frozen permission distribution.pay','CRITICAL'),
  ('distribution.reverse','distribution','V6.1 frozen permission distribution.reverse','CRITICAL'),
  ('cost_catalog.manage','cost_catalog','V6.1 frozen permission cost_catalog.manage','HIGH'),
  ('revenue_policy.manage','revenue_policy','V6.1 frozen permission revenue_policy.manage','HIGH')
ON CONFLICT (permission_code) DO UPDATE SET
  domain = EXCLUDED.domain,
  description = EXCLUDED.description,
  risk_level = EXCLUDED.risk_level;

INSERT INTO role_permissions(role_code, permission_code, access_scope) VALUES
  ('PLATFORM_ADMIN','audit.read','ALL'),
  ('PLATFORM_ADMIN','tenant.suspend','DUAL'),
  ('PLATFORM_ADMIN','merchant.intake.create','ALL'),
  ('PLATFORM_ADMIN','merchant.intake.read','ALL'),
  ('PLATFORM_ADMIN','merchant.intake.write','ALL'),
  ('PLATFORM_ADMIN','merchant.intake.confirm','ALL'),
  ('PLATFORM_ADMIN','revenue_right.read_own','ALL'),
  ('PLATFORM_ADMIN','revenue_right.read_all','ALL'),
  ('PLATFORM_ADMIN','revenue_right.create','ALL'),
  ('PLATFORM_ADMIN','revenue_right.transfer_request','ALL'),
  ('PLATFORM_ADMIN','revenue_right.transfer_approve','DUAL'),
  ('PLATFORM_ADMIN','revenue_right.suspend','DUAL'),
  ('PLATFORM_ADMIN','distribution.read_own','ALL'),
  ('PLATFORM_ADMIN','distribution.read_all','ALL'),
  ('PLATFORM_ADMIN','distribution.cost.read','ALL'),
  ('PLATFORM_ADMIN','distribution.lock','ALL'),
  ('PLATFORM_ADMIN','distribution.pay','ALL'),
  ('PLATFORM_ADMIN','distribution.reverse','ALL'),
  ('PLATFORM_ADMIN','cost_catalog.manage','DUAL'),
  ('PLATFORM_ADMIN','revenue_policy.manage','DUAL'),
  ('PLATFORM_OPS','delivery.read','JIT_READ'),
  ('PLATFORM_OPS','merchant_profile.manage','JIT_READ'),
  ('PLATFORM_OPS','miniprogram.manage','JIT_READ'),
  ('PLATFORM_OPS','geo.read','JIT_READ'),
  ('PLATFORM_OPS','customer_service.read','JIT_READ'),
  ('PLATFORM_OPS','customer_profile.read','JIT_READ'),
  ('PLATFORM_OPS','order.read','JIT_READ'),
  ('PLATFORM_OPS','report.value.read','JIT_READ'),
  ('PLATFORM_OPS','audit.read','JIT_READ'),
  ('PLATFORM_OPS','support.jit_read','JIT_READ'),
  ('PLATFORM_OPS','merchant.intake.read','JIT_READ'),
  ('PLATFORM_OPS','revenue_right.read_all','JIT_READ'),
  ('PLATFORM_OPS','distribution.read_all','JIT_READ'),
  ('PLATFORM_FINANCE','delivery.read','JIT_READ'),
  ('PLATFORM_FINANCE','order.read','JIT_READ'),
  ('PLATFORM_FINANCE','finance.reconcile','JIT_READ'),
  ('PLATFORM_FINANCE','settlement.approve','DUAL'),
  ('PLATFORM_FINANCE','report.value.read','JIT_READ'),
  ('PLATFORM_FINANCE','audit.read','JIT_READ'),
  ('PLATFORM_FINANCE','revenue_right.read_all','ALL'),
  ('PLATFORM_FINANCE','revenue_right.transfer_approve','DUAL'),
  ('PLATFORM_FINANCE','revenue_right.suspend','DUAL'),
  ('PLATFORM_FINANCE','distribution.read_all','ALL'),
  ('PLATFORM_FINANCE','distribution.cost.read','ALL'),
  ('PLATFORM_FINANCE','distribution.lock','DUAL'),
  ('PLATFORM_FINANCE','distribution.pay','DUAL'),
  ('PLATFORM_FINANCE','distribution.reverse','DUAL'),
  ('PLATFORM_FINANCE','cost_catalog.manage','DUAL'),
  ('PLATFORM_FINANCE','revenue_policy.manage','DUAL'),
  ('CHANNEL_PARTNER','delivery.read','ASSIGNED'),
  ('CHANNEL_PARTNER','delivery.execute','ASSIGNED'),
  ('CHANNEL_PARTNER','merchant_profile.manage','ASSIGNED'),
  ('CHANNEL_PARTNER','geo.read','ASSIGNED'),
  ('CHANNEL_PARTNER','order.read','ASSIGNED'),
  ('CHANNEL_PARTNER','report.value.read','ASSIGNED'),
  ('CHANNEL_PARTNER','merchant.intake.create','ASSIGNED'),
  ('CHANNEL_PARTNER','merchant.intake.read','ASSIGNED'),
  ('CHANNEL_PARTNER','merchant.intake.write','ASSIGNED'),
  ('CHANNEL_PARTNER','revenue_right.read_own','ASSIGNED'),
  ('CHANNEL_PARTNER','revenue_right.transfer_request','ASSIGNED'),
  ('CHANNEL_PARTNER','distribution.read_own','ASSIGNED'),
  ('CHANNEL_PARTNER','distribution.cost.read','ASSIGNED'),
  ('MERCHANT_OWNER','delivery.read','TENANT'),
  ('MERCHANT_OWNER','delivery.create','TENANT'),
  ('MERCHANT_OWNER','delivery.execute','TENANT'),
  ('MERCHANT_OWNER','delivery.accept','TENANT'),
  ('MERCHANT_OWNER','merchant_profile.manage','TENANT'),
  ('MERCHANT_OWNER','miniprogram.manage','TENANT'),
  ('MERCHANT_OWNER','miniprogram.release.submit','TENANT'),
  ('MERCHANT_OWNER','miniprogram.release.publish','TENANT'),
  ('MERCHANT_OWNER','miniprogram.release.rollback','DUAL'),
  ('MERCHANT_OWNER','geo.read','TENANT'),
  ('MERCHANT_OWNER','geo.publish','TENANT'),
  ('MERCHANT_OWNER','customer_service.read','TENANT'),
  ('MERCHANT_OWNER','customer_service.accept','TENANT'),
  ('MERCHANT_OWNER','customer_service.send','TENANT'),
  ('MERCHANT_OWNER','customer_service.close','TENANT'),
  ('MERCHANT_OWNER','customer_profile.read','TENANT'),
  ('MERCHANT_OWNER','customer_profile.export','DUAL'),
  ('MERCHANT_OWNER','order.read','TENANT'),
  ('MERCHANT_OWNER','order.manage','TENANT'),
  ('MERCHANT_OWNER','refund.request','TENANT'),
  ('MERCHANT_OWNER','refund.approve','TENANT'),
  ('MERCHANT_OWNER','verification.execute','TENANT'),
  ('MERCHANT_OWNER','reward_rule.manage','TENANT'),
  ('MERCHANT_OWNER','finance.reconcile','TENANT'),
  ('MERCHANT_OWNER','settlement.approve','DUAL'),
  ('MERCHANT_OWNER','report.value.read','TENANT'),
  ('MERCHANT_OWNER','member.manage','TENANT'),
  ('MERCHANT_OWNER','role.manage','TENANT'),
  ('MERCHANT_OWNER','plugin.install','TENANT'),
  ('MERCHANT_OWNER','plugin.permission.grant','TENANT'),
  ('MERCHANT_OWNER','audit.read','TENANT'),
  ('MERCHANT_OWNER','merchant.intake.create','TENANT'),
  ('MERCHANT_OWNER','merchant.intake.read','TENANT'),
  ('MERCHANT_OWNER','merchant.intake.write','TENANT'),
  ('MERCHANT_OWNER','merchant.intake.confirm','TENANT'),
  ('STORE_MANAGER','delivery.read','STORE'),
  ('STORE_MANAGER','delivery.execute','STORE'),
  ('STORE_MANAGER','merchant_profile.manage','STORE'),
  ('STORE_MANAGER','geo.read','STORE'),
  ('STORE_MANAGER','geo.publish','STORE'),
  ('STORE_MANAGER','customer_service.read','STORE'),
  ('STORE_MANAGER','customer_service.accept','STORE'),
  ('STORE_MANAGER','customer_service.send','STORE'),
  ('STORE_MANAGER','customer_service.close','STORE'),
  ('STORE_MANAGER','customer_profile.read','STORE'),
  ('STORE_MANAGER','order.read','STORE'),
  ('STORE_MANAGER','order.manage','STORE'),
  ('STORE_MANAGER','refund.request','STORE'),
  ('STORE_MANAGER','refund.approve','CONDITIONAL'),
  ('STORE_MANAGER','verification.execute','STORE'),
  ('STORE_MANAGER','finance.reconcile','STORE'),
  ('STORE_MANAGER','report.value.read','STORE'),
  ('STORE_MANAGER','member.manage','STORE'),
  ('STORE_MANAGER','audit.read','STORE'),
  ('STORE_MANAGER','merchant.intake.read','STORE'),
  ('STORE_MANAGER','merchant.intake.write','STORE'),
  ('CUSTOMER_SERVICE','customer_service.read','STORE'),
  ('CUSTOMER_SERVICE','customer_service.accept','STORE'),
  ('CUSTOMER_SERVICE','customer_service.send','STORE'),
  ('CUSTOMER_SERVICE','customer_service.close','STORE'),
  ('CUSTOMER_SERVICE','customer_profile.read','STORE'),
  ('CUSTOMER_SERVICE','order.read','STORE'),
  ('CUSTOMER_SERVICE','report.value.read','STORE'),
  ('FINANCE','delivery.read','TENANT'),
  ('FINANCE','geo.read','TENANT'),
  ('FINANCE','customer_profile.read','TENANT'),
  ('FINANCE','customer_profile.export','DUAL'),
  ('FINANCE','order.read','TENANT'),
  ('FINANCE','refund.request','TENANT'),
  ('FINANCE','refund.approve','TENANT'),
  ('FINANCE','reward_rule.manage','TENANT'),
  ('FINANCE','finance.reconcile','TENANT'),
  ('FINANCE','settlement.approve','DUAL'),
  ('FINANCE','report.value.read','TENANT'),
  ('FINANCE','audit.read','TENANT'),
  ('MARKETER','delivery.read','STORE'),
  ('MARKETER','merchant_profile.manage','STORE'),
  ('MARKETER','miniprogram.manage','STORE'),
  ('MARKETER','geo.read','STORE'),
  ('MARKETER','geo.publish','STORE'),
  ('MARKETER','customer_service.read','STORE'),
  ('MARKETER','customer_profile.read','STORE'),
  ('MARKETER','order.read','STORE'),
  ('MARKETER','order.manage','STORE'),
  ('MARKETER','reward_rule.manage','STORE'),
  ('MARKETER','report.value.read','STORE'),
  ('VERIFIER','order.read','OWN'),
  ('VERIFIER','verification.execute','STORE'),
  ('AUDITOR','delivery.read','TENANT'),
  ('AUDITOR','merchant_profile.manage','TENANT'),
  ('AUDITOR','miniprogram.manage','TENANT'),
  ('AUDITOR','geo.read','TENANT'),
  ('AUDITOR','customer_service.read','TENANT'),
  ('AUDITOR','customer_profile.read','TENANT'),
  ('AUDITOR','order.read','TENANT'),
  ('AUDITOR','reward_rule.manage','TENANT'),
  ('AUDITOR','finance.reconcile','TENANT'),
  ('AUDITOR','report.value.read','TENANT'),
  ('AUDITOR','audit.read','TENANT'),
  ('PLUGIN_RUNTIME','merchant_profile.manage','GRANT'),
  ('PLUGIN_RUNTIME','miniprogram.manage','GRANT'),
  ('PLUGIN_RUNTIME','geo.read','GRANT'),
  ('PLUGIN_RUNTIME','geo.publish','GRANT'),
  ('PLUGIN_RUNTIME','customer_service.read','GRANT'),
  ('PLUGIN_RUNTIME','customer_service.send','GRANT'),
  ('PLUGIN_RUNTIME','customer_profile.read','GRANT'),
  ('PLUGIN_RUNTIME','order.read','GRANT'),
  ('PLUGIN_RUNTIME','order.manage','GRANT'),
  ('PLUGIN_RUNTIME','reward_rule.manage','GRANT'),
  ('PLUGIN_RUNTIME','report.value.read','GRANT'),
  ('BUSINESS_DEVELOPER','delivery.read','ASSIGNED'),
  ('BUSINESS_DEVELOPER','delivery.execute','ASSIGNED'),
  ('BUSINESS_DEVELOPER','merchant_profile.manage','ASSIGNED'),
  ('BUSINESS_DEVELOPER','geo.read','ASSIGNED'),
  ('BUSINESS_DEVELOPER','order.read','ASSIGNED'),
  ('BUSINESS_DEVELOPER','report.value.read','ASSIGNED'),
  ('BUSINESS_DEVELOPER','merchant.intake.create','ASSIGNED'),
  ('BUSINESS_DEVELOPER','merchant.intake.read','ASSIGNED'),
  ('BUSINESS_DEVELOPER','merchant.intake.write','ASSIGNED'),
  ('BUSINESS_DEVELOPER','revenue_right.read_own','ASSIGNED'),
  ('BUSINESS_DEVELOPER','revenue_right.transfer_request','ASSIGNED'),
  ('BUSINESS_DEVELOPER','distribution.read_own','ASSIGNED'),
  ('BUSINESS_DEVELOPER','distribution.cost.read','ASSIGNED'),
  ('INVESTMENT_OPERATOR','delivery.read','ASSIGNED'),
  ('INVESTMENT_OPERATOR','delivery.execute','ASSIGNED'),
  ('INVESTMENT_OPERATOR','merchant_profile.manage','ASSIGNED'),
  ('INVESTMENT_OPERATOR','geo.read','ASSIGNED'),
  ('INVESTMENT_OPERATOR','order.read','ASSIGNED'),
  ('INVESTMENT_OPERATOR','report.value.read','ASSIGNED'),
  ('INVESTMENT_OPERATOR','merchant.intake.create','ASSIGNED'),
  ('INVESTMENT_OPERATOR','merchant.intake.read','ASSIGNED'),
  ('INVESTMENT_OPERATOR','merchant.intake.write','ASSIGNED'),
  ('INVESTMENT_OPERATOR','revenue_right.read_own','ASSIGNED'),
  ('INVESTMENT_OPERATOR','revenue_right.read_all','REGION'),
  ('INVESTMENT_OPERATOR','revenue_right.transfer_request','ASSIGNED'),
  ('INVESTMENT_OPERATOR','distribution.read_own','ASSIGNED'),
  ('INVESTMENT_OPERATOR','distribution.read_all','REGION'),
  ('INVESTMENT_OPERATOR','distribution.cost.read','ASSIGNED'),
  ('REGIONAL_PROVIDER','delivery.read','ASSIGNED'),
  ('REGIONAL_PROVIDER','delivery.execute','ASSIGNED'),
  ('REGIONAL_PROVIDER','merchant_profile.manage','ASSIGNED'),
  ('REGIONAL_PROVIDER','geo.read','ASSIGNED'),
  ('REGIONAL_PROVIDER','order.read','ASSIGNED'),
  ('REGIONAL_PROVIDER','report.value.read','ASSIGNED'),
  ('REGIONAL_PROVIDER','merchant.intake.create','ASSIGNED'),
  ('REGIONAL_PROVIDER','merchant.intake.read','ASSIGNED'),
  ('REGIONAL_PROVIDER','merchant.intake.write','ASSIGNED'),
  ('REGIONAL_PROVIDER','revenue_right.read_own','ASSIGNED'),
  ('REGIONAL_PROVIDER','revenue_right.transfer_request','ASSIGNED'),
  ('REGIONAL_PROVIDER','distribution.read_own','ASSIGNED'),
  ('REGIONAL_PROVIDER','distribution.cost.read','ASSIGNED')
ON CONFLICT (role_code, permission_code) DO UPDATE SET access_scope = EXCLUDED.access_scope;

INSERT INTO schema_migrations(version, checksum)
VALUES ('0008_identity_access_and_usage', encode(digest('lequbao-v6.1-0008', 'sha256'), 'hex'))
ON CONFLICT (version) DO NOTHING;

COMMIT;
